import {initCFD} from './cfd.js';
import {initSessionUI} from './session.js';
initSessionUI();
import {specs,presets,camber,thick,profile,section,build,stl,validate,isPritchard,getSpecs,getPresets,analyze,frame,reference} from './geometry.js';
const $=s=>document.querySelector(s);let p={...presets.baseline},mesh,mode='solid',az=-.72,el=.16,zoom=1,auto=false,z=.5;const canvas=$('#blade'),ctx=canvas.getContext('2d');let toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function renderControls(){
 $('#geometry-error').textContent='';
 const current=getSpecs(p);
 $('#parameter-groups').innerHTML=current.map(([title,no,items])=>`<div class="parameter-group"><h3><span>${no}</span>${title}</h3>${items.map(([k,label,min,max,step,unit])=>`<div class="control"><div class="control-line"><label for="r-${k}">${label}</label><div class="number-wrap"><input id="n-${k}" aria-label="${label}数值" type="number" min="${min}" max="${max}" step="any" value="${Number(p[k].toFixed(5))}"><span>${unit}</span></div></div><input id="r-${k}" aria-label="${label}" type="range" min="${min}" max="${max}" step="${step}" value="${Number(p[k].toFixed(5))}"></div>`).join('')}</div>`).join('');
 if(isPritchard(p))$('#parameter-groups').insertAdjacentHTML('beforeend','<details class="span-settings"><summary>三维拉伸展示（非11参数）</summary><label for="extrusion-height">拉伸展宽 / mm</label><input id="extrusion-height" type="number" min="30" max="160" value="'+p.height+'"></details>');
 const change=(k,v)=>{try{const next=validate({...p,[k]:v});const nextMesh=build(next);p=next;mesh=nextMesh;custom();sync();$('#geometry-error').textContent='';}catch(err){$('#geometry-error').textContent=err.message;sync();}};
 for(const [,,items] of current)for(const [k] of items){$('#r-'+k).oninput=e=>change(k,Number(e.target.value));$('#n-'+k).onchange=e=>{if(e.target.value===''){$('#geometry-error').textContent='请输入数值';sync();return;}change(k,Number(e.target.value));};}
 if($('#extrusion-height'))$('#extrusion-height').onchange=e=>change('height',Number(e.target.value));
 $('#geometry-model').value=isPritchard(p)?'pritchard-1985':'legacy';
 $('#preset').innerHTML=isPritchard(p)?'<option value="baseline">Pritchard 图19 · 参考截面</option><option value="slender">轴向弦长调整示例</option><option value="wide">进口半楔角调整示例</option>':'<option value="baseline">旧模型 · 基准叶片</option><option value="slender">旧模型 · 细长叶片</option><option value="wide">旧模型 · 宽弦叶片</option>';
}
$('#geometry-model').onchange=e=>{p=e.target.value==='pritchard-1985'?{...reference}:{chord:50,thickness:16,position:35,inlet:48,outlet:-42,stagger:22,height:90,taper:.76,twist:-18,sweep:7,lean:5};renderControls();sync();$('#preset').value='baseline';$('#geometry-error').textContent='';};
function custom(){$('#design-name').textContent='自定义叶片';$('#preset').value=''}function sync(){for(const[,,items]of getSpecs(p))for(const[k]of items){$('#r-'+k).value=p[k];$('#n-'+k).value=Number(p[k].toFixed(5))}update()}
$('#preset').onchange=e=>{$('#geometry-error').textContent='';p={...getPresets(p)[e.target.value]};$('#design-name').textContent=e.target.selectedOptions[0].text.split(' · ')[0];sync()};$('#reset').onclick=()=>{$('#geometry-error').textContent='';p={...getPresets(p).baseline};$('#preset').value='baseline';$('#design-name').textContent='基准叶片';sync();toast('已恢复基准参数')};
function update(){$('.view-caption span').textContent=isPritchard(p)?'Pritchard截面 · 等截面直线拉伸':'参数化截面展向堆叠';document.dispatchEvent(new Event('aeroblade:designchange'));mesh=build(p);$('#m-height').innerHTML=p.height.toFixed(0)+'<em>mm</em>';$('#m-chord').innerHTML=frame(p).chord.toFixed(0)+'<em>mm</em>';$('#m-ar').textContent=(p.height/(frame(p).chord*(1+frame(p).taper)/2)).toFixed(2);$('#m-volume').innerHTML=(mesh.volume/1000).toFixed(2)+'<em>cm³</em>';$('#mesh-count').textContent=mesh.vertices.length.toLocaleString()+' 顶点 · '+mesh.faces.length.toLocaleString()+' 三角面';$('#validity').textContent=isPritchard(p)?'五段轮廓闭合 · 无采样自交 · C¹连接':'旧模型 · 叶身闭合三角网格';$('#model-note').textContent=isPritchard(p)?'Pritchard 1985：三圆弧与两三次多项式。半径与叶片数确定节距；当前三维模型为同一截面直线拉伸，未实现径向多截面设计。':'旧版概念几何模型：弯度线加厚度分布，非Pritchard方法。';$('#chord-label').textContent=isPritchard(p)?'轴向弦长':'根部弦长';$('#height-label').textContent=isPritchard(p)?'拉伸展宽':'叶高';drawCharts();draw()}
const svgline=(a,b,color,width=1,extra='')=>`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${color}" stroke-width="${width}" ${extra}/>`;
function drawPritchardCharts(){
 const g=analyze(p),pts=g.points;
 function outline(q,offset=0){return q.map(([x,y])=>[x,y+offset]);}
 function plot(svg,curves,throat=false){
  const W=420,H=180,pad=28,all=curves.flatMap(c=>c.points),xs=all.map(q=>q[0]),ys=all.map(q=>q[1]),lo=[Math.min(...xs),Math.min(...ys)],hi=[Math.max(...xs),Math.max(...ys)],scale=Math.min((W-pad*2)/(hi[0]-lo[0]),(H-pad*2)/(hi[1]-lo[1]));
  const pt=([x,y])=>[W/2+(x-(lo[0]+hi[0])/2)*scale,H/2-(y-(lo[1]+hi[1])/2)*scale];
  svg.setAttribute('viewBox',`0 0 ${W} ${H}`);
  let out=curves.map(c=>`<polyline points="${c.points.map(q=>pt(q).join(',')).join(' ')}" fill="${c.fill||'none'}" stroke="${c.color}" stroke-width="1.7"/>`).join('');
  if(throat){const q=g.keyPoints[1],ctr=[p.axialChord-p.trailingRadius,g.pitch],d=Math.hypot(q[0]-ctr[0],q[1]-ctr[1]),b=ctr.map((v,i)=>v+(q[i]-v)*p.trailingRadius/d);out+=svgline(pt(q),pt(b),'#a45716',2);}
  else for(const [j,q] of g.keyPoints.entries()){const a=pt(q);out+=`<circle cx="${a[0]}" cy="${a[1]}" r="2.5" fill="#1d4b90"/><text x="${a[0]+5}" y="${a[1]-5}" font-size="13" fill="#334a64">${j+1}</text>`;}
  out+=`<text x="8" y="174" font-size="13" fill="#526780">x / mm → · y / mm ↑</text>`;svg.innerHTML=out;
 }
 plot($('#profile'),g.segments.map((seg,i)=>({points:seg.points,color:['#2774cf','#a45716','#6b53a6','#19866f','#6b53a6'][i]})));
 $('.chart-title').innerHTML='Pritchard 截面 <span>连接点 1–5</span>';
 $('.legend').innerHTML='<span>蓝：吸力面</span><span>绿：压力面</span><span>棕：喉后圆弧</span>';
 $('#section-metrics').innerHTML=[['节距 s',g.pitch.toFixed(3)+' mm'],['几何弦长 c',g.chord.toFixed(3)+' mm'],['派生安装角 ξ',g.stagger.toFixed(3)+'°'],['尾缘半楔角 εout',g.exitHalfWedge.toFixed(3)+'°'],['截面积（离散）',g.area.toFixed(3)+' mm²']].map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');
 $('.distribution-heading h3').textContent='叶栅节距与指定喉道';
 plot($('#distribution'),[{points:[...pts,pts[0]],color:'#2774cf'},{points:outline([...pts,pts[0]],g.pitch),color:'#9baabc'}],true);
}
function drawCharts(){if(isPritchard(p)){drawPritchardCharts();return;}$('#profile').setAttribute('viewBox','0 0 320 225');$('#distribution').setAttribute('viewBox','0 0 320 140');$('.chart-title').innerHTML='局部截面 <span>x/c · y/c</span>';$('.legend').innerHTML='<span>叶型轮廓</span><span>弯度线</span>';$('.distribution-heading h3').textContent='展向弦长分布';const s=section(p,z),pt=([x,y])=>[30+x*265,159-y*205];let out='';for(let x=0;x<=1;x+=.2){out+=svgline(pt([x,-.15]),pt([x,.55]),'#e8edf4');out+=`<text x="${pt([x,0])[0]}" y="211" text-anchor="middle" fill="#526780" font-size="18">${x.toFixed(1)}</text>`}for(let y=-.1;y<=.5;y+=.1)out+=svgline(pt([0,y]),pt([1,y]),'#e8edf4');out+=svgline(pt([0,0]),pt([1,0]),'#c6d0df',1,'stroke-dasharray="4 4"');const path=mesh.shape.map(a=>pt(a).join(',')).join(' ');out+=`<polygon points="${path}" fill="#e7effd" stroke="#4789f2" stroke-width="2"/>`;out+=`<polyline points="${Array.from({length:65},(_,i)=>pt([i/64,camber(i/64,p)]).join(',')).join(' ')}" fill="none" stroke="#7f97b6" stroke-width="1.3" stroke-dasharray="4 3"/>`;$ ('#profile').innerHTML=out;
let maxT=0,maxY=0;for(let i=0;i<=1000;i++){maxT=Math.max(maxT,thick(i/1000,p));maxY=Math.max(maxY,camber(i/1000,p))}$('#section-metrics').innerHTML=[['局部弦长',s.chord.toFixed(2)+' mm'],['局部 y 向最大厚度',(maxT*s.chord).toFixed(2)+' mm'],['最大弯度',(maxY*100).toFixed(1)+'% c'],['局部安装角',s.angle.toFixed(1)+'°'],['截面高度',(p.height*z).toFixed(1)+' mm']].map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');const cmax=Math.max(p.chord,p.chord*p.taper)*1.15,dp=(t,c)=>[38+245*t,110-c/cmax*90];out='';for(let i=0;i<3;i++){const t=i/2;out+=svgline([38,20+i*45],[283,20+i*45],'#edf0f5');out+=`<text x="25" y="${24+i*45}" fill="#526780" font-size="18" text-anchor="end">${(cmax*(1-i/2)).toFixed(0)}</text><text x="${38+245*t}" y="130" fill="#526780" font-size="18" text-anchor="middle">${t*100}%</text>`}const a=dp(0,p.chord),b=dp(1,p.chord*p.taper),c=dp(z,s.chord);out+=`<polygon points="38,110 ${a} ${b} 283,110" fill="#edf3ff"/>`+svgline(a,b,'#528bef',2)+svgline([c[0],110],c,'#85acef',1,'stroke-dasharray="3 3"')+`<circle cx="${c[0]}" cy="${c[1]}" r="4" fill="#4285ee" stroke="white" stroke-width="2"/>`;$('#distribution').innerHTML=out}
$('#span').oninput=e=>{z=+e.target.value/100;$('#span-value').textContent=e.target.value+'%';drawCharts();draw()};
function draw(){if(!mesh)return;const view=frame(p);const W=canvas.clientWidth,H=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(W*dpr)||canvas.height!==Math.round(H*dpr)){canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);const scale=Math.min(W/(view.chord*2.4),H/(view.height*1.62))*zoom;const tr=v=>{const x=v[0]-view.sweep/2,y=v[1]-view.lean/2;const X=x*Math.cos(az)-y*Math.sin(az),Y=x*Math.sin(az)+y*Math.cos(az);return [W*.5+X*scale,H*.52+(-v[2]*Math.cos(el)+Y*Math.sin(el))*scale,Y*Math.cos(el)+v[2]*Math.sin(el)]};const line=(a,b,col,w=1)=>{ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.strokeStyle=col;ctx.lineWidth=w;ctx.stroke()};const extent=Math.max(view.chord,view.height)*.8;for(let i=-6;i<=6;i++){const t=i*extent/6;line(tr([-extent,t,-view.height/2-4]),tr([extent,t,-view.height/2-4]),'#33435866');line(tr([t,-extent,-view.height/2-4]),tr([t,extent,-view.height/2-4]),'#33435866')}
const verts=mesh.vertices.map(tr);if(mode!=='sections'){const sorted=mesh.faces.map(f=>({f,depth:f.reduce((s,i)=>s+verts[i][2],0)/3})).sort((a,b)=>b.depth-a.depth);for(const {f}of sorted){const [a,b,c]=f.map(i=>verts[i]);ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.lineTo(c[0],c[1]);ctx.closePath();if(mode==='solid'){const va=mesh.vertices[f[0]],vb=mesh.vertices[f[1]],vc=mesh.vertices[f[2]],u=vb.map((v,i)=>v-va[i]),v=vc.map((v,i)=>v-va[i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],nn=Math.hypot(...n)||1;const light=Math.abs((n[0]*.25-n[1]*.83+n[2]*.5)/nn),l=32+light*43;ctx.fillStyle=`hsl(212 22% ${l}%)`;ctx.fill();ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=.55;ctx.stroke()}else{ctx.strokeStyle='#7cafdd55';ctx.lineWidth=.45;ctx.stroke()}}}
if(mode==='sections'){for(let j=0;j<=mesh.layers;j+=3){ctx.beginPath();for(let i=0;i<mesh.len;i++){const a=verts[j*mesh.len+i];i?ctx.lineTo(a[0],a[1]):ctx.moveTo(a[0],a[1])}ctx.closePath();ctx.strokeStyle='#7ab5ec';ctx.lineWidth=1.1;ctx.stroke()}for(let i=0;i<mesh.len;i+=16)for(let j=0;j<mesh.layers;j++)line(verts[j*mesh.len+i],verts[(j+1)*mesh.len+i],'#668bb344')}
const ss=section(p,z),ang=ss.angle*Math.PI/180;ctx.beginPath();mesh.shape.forEach(([x,y],i)=>{const X=(x-.5)*ss.chord,Y=y*ss.chord,a=tr([X*Math.cos(ang)-Y*Math.sin(ang)+view.sweep*z,Y*Math.cos(ang)+X*Math.sin(ang)+view.lean*z,view.height*z-view.height/2]);i?ctx.lineTo(a[0],a[1]):ctx.moveTo(a[0],a[1])});ctx.closePath();ctx.strokeStyle='#74beff';ctx.lineWidth=1.5;ctx.setLineDash(mode==='solid'?[4,3]:[]);ctx.stroke();ctx.setLineDash([]);
const origin=[W-64,H-67];const axes=[[[1,0,0],'#ee9b89','X'],[[0,1,0],'#8dbbb1','Y'],[[0,0,1],'#75aafa','Z']];const o=tr([0,0,0]);for(const [v,color,label]of axes){const end=tr(v.map(x=>x*25/scale)),b=[origin[0]+end[0]-o[0],origin[1]+end[1]-o[1]];line(origin,b,color,1.4);ctx.fillStyle=color;ctx.font='12px sans-serif';ctx.fillText(label,b[0]+3,b[1]-3)}}
new ResizeObserver(draw).observe(canvas);let pointers=new Map(),last=null;canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);last=[e.clientX,e.clientY];canvas.style.cursor='grabbing'};canvas.onpointermove=e=>{if(!last)return;az+=(e.clientX-last[0])*.008;el=Math.max(-1.3,Math.min(1.3,el+(e.clientY-last[1])*.006));last=[e.clientX,e.clientY];draw()};canvas.onpointerup=canvas.onpointercancel=()=>{last=null;canvas.style.cursor='grab'};canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.45,Math.min(2.8,zoom*Math.exp(-e.deltaY*.001)));draw()};canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')az-=.12;if(e.key==='ArrowRight')az+=.12;if(e.key==='ArrowUp')el=Math.min(1.3,el+.1);if(e.key==='ArrowDown')el=Math.max(-1.3,el-.1);if(e.key==='+')zoom=Math.min(2.8,zoom*1.1);if(e.key==='-')zoom=Math.max(.45,zoom/1.1);draw()};$('#home').onclick=()=>{az=-.72;el=.16;zoom=1;draw()};$('#zoom-in').onclick=()=>{zoom=Math.min(2.8,zoom*1.15);draw()};$('#zoom-out').onclick=()=>{zoom=Math.max(.45,zoom/1.15);draw()};let lastFrame=0;function spin(time){if(!auto)return;if(time-lastFrame>33){az+=.006;draw();lastFrame=time}requestAnimationFrame(spin)}$('#rotate').onclick=()=>{auto=!auto;$('#rotate').classList.toggle('active',auto);$('#rotate').setAttribute('aria-pressed',auto);if(auto)requestAnimationFrame(spin)};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});draw()});
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('已导出 '+name)}function csv(){if(isPritchard(p)){download('pritchard-section-mm.csv','x_mm,y_mm\n'+analyze(p).points.map(q=>q.map(v=>v.toFixed(9)).join(',')).join('\n'),'text/csv');return;}const s=section(p,z);download('aeroblade-section-'+Math.round(z*100)+'.csv','x_mm,y_mm,span_fraction\n'+profile(p).map(([x,y])=>[(x*s.chord).toFixed(7),(y*s.chord).toFixed(7),z].join(',')).join('\n'),'text/csv')}$('#csv').onclick=csv;function modal(title,html){$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=html;$('#dialog').showModal()}$('#close-dialog').onclick=()=>$('#dialog').close();$('#dialog').onclick=e=>{if(e.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#dialog').close()}};
$('#export').onclick=()=>{modal('导出设计','<p>选择需要的设计数据。STL 为闭合叶身三角网格，坐标单位为毫米，不含榫根与冷却孔。</p><button id="json-out">参数文件 JSON <small>　可重新导入并编辑</small></button><button id="stl-out">三维叶身 STL <small>　用于几何查看与后续处理</small></button><button id="csv-out">当前截面 CSV <small>　局部未旋转坐标</small></button>');$('#json-out').onclick=()=>download('aeroblade-design.json',JSON.stringify({schema:isPritchard(p)?'aeroblade-pritchard-v1':'aeroblade-v1',units:{length:'mm',angle:'deg'},parameters:p},null,2),'application/json');$('#stl-out').onclick=()=>download('aeroblade-blade-mm.stl',stl(mesh),'model/stl');$('#csv-out').onclick=csv};$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>100000)throw Error('文件过大，请选择参数 JSON');const data=JSON.parse(await f.text());if(!['aeroblade-v1','aeroblade-pritchard-v1'].includes(data.schema))throw Error('不支持此设计格式');if((data.schema==='aeroblade-pritchard-v1')!==isPritchard(data.parameters))throw Error('文件格式与几何模型标识不一致');if(data.units?.length!=='mm'||data.units?.angle!=='deg')throw Error('参数单位必须为mm和deg');const next=validate(data.parameters);build(next);p=next;renderControls();custom();sync();toast('设计参数已导入')}catch(err){toast('导入失败：'+err.message)}e.target.value=''};
$('#method').onclick=()=>{if(isPritchard(p)){modal('Pritchard 1985 截面模型','<p>依据 L. J. Pritchard, An Eleven Parameter Axial Turbine Airfoil Geometry Model, ASME 85-GT-219，式1–16及附录C。<a href="https://doi.org/10.1115/85-GT-219" target="_blank" rel="noopener">原论文 ↗</a></p><p>11个参数控制五段轮廓：前/尾缘圆弧、喉后吸力面圆弧与两段三次多项式。进口楔角输入为半角；尾缘半楔角由C¹闭合方程求出。角度为轴向有符号切线角，长度单位mm。</p><p>默认值来自图19参考算例，统一换算mm，喉道按该算例默认公式展开；并非最佳叶片。当前支持出口负角的常规叶型分支，不使用原FORTRAN隐式默认值。三维展示为等截面直线拉伸。</p>');return;}modal('旧版概念几何模型','<p><strong>截面模型</strong><br>弯度线为三次 Hermite 曲线，两端弯度为零，端点切线由前、后缘弯度线角控制。厚度使用可移动峰值的幂函数，沿局部 y 方向叠加；尾缘添加 0.4% 弦长的有限厚度。</p><p><strong>展向模型</strong><br>截面弦长、安装角及轴向／周向积叠偏移沿展向线性变化。安装角绕半弦点旋转。展弦比使用叶高除以平均弦长，体积由闭合三角网格积分。</p><p><strong>适用范围</strong><br>用于参数探索、概念几何可视化与算法原型。前后缘角为几何切线角，不等于流动进出口角；曲面需经制造级 CAD 重构和网格质量检查后才能用于工程流程。未进行气动、强度、热负荷或可制造性验证。</p>');};renderControls();sync();

initCFD(()=>({...p}),parameters=>{const next=validate(parameters);build(next);p=next;renderControls();custom();sync();});

document.addEventListener('aeroblade:sessionchange',()=>{p={...presets.baseline};renderControls();custom();sync();});
