import {sessionFetch} from './session.js';
import {BatchRequests} from './batch-state.js';
import {validate,analyze,pritchardSpecs} from './geometry.js';
const FIELDS=pritchardSpecs.flatMap(g=>g[2]);
const CONDITION_FIELDS=[['inletTotalPressure','入口总压 / Pa',100100,100500],['inletTotalTemperature','入口总温 / K',290,310],['outletStaticPressure','出口静压 / Pa',100000,100000],['iterations','迭代上限',100,5000]];
const STATUS={ready:'待启动',pending:'待提交',submitting:'等待确认',queued:'排队',preparing:'准备算例',running:'运行',packaging:'整理结果',paused:'已暂停',cancelling:'取消中',completed:'完成',failed:'失败',cancelled:'已取消',interrupted:'重启中断',unknown:'记录待核对'};
const terminal=s=>['completed','failed','cancelled','interrupted','unknown'].includes(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(v)?Number(v.toPrecision(7)).toString():'—';
function shape(p){try{const points=analyze(p).points,xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),lo=Math.min(...xs),bottom=Math.min(...ys),scale=Math.min(135/(Math.max(...xs)-lo),75/(Math.max(...ys)-bottom));return `<svg viewBox="0 0 150 90" role="img" aria-label="叶型预览"><polygon points="${points.map(p=>`${7+(p[0]-lo)*scale},${82-(p[1]-bottom)*scale}`).join(' ')}" fill="#edf3ff" stroke="#386ac3" stroke-width="1.2"/></svg>`;}catch{return '<span>几何不可预览</span>';}}

export function initBatchWorkflow({getDesign,applyDesign,initialPanel,cfdPanel,aiPanel,openCFD,openAI,showTraining,buildBatchDataset}){
  const $=s=>document.querySelector(s);let baseline=null,provenance={},bundle=null,editRevision=0,previewRevision=-1,generationTask=null,epoch=0,pollTimer=null,generationTimer=null,ready=false,batch=null,batchList=[],busy=false,listSerial=0,hasSession=false;
  const requests=new BatchRequests(()=>epoch,()=>editRevision);
  const initialButton=document.createElement('button');initialButton.id='initial-batch';initialButton.textContent='批量方案';initialPanel.querySelector('.initial-topbar>div:last-child').prepend(initialButton);
  const dialog=document.createElement('dialog');dialog.id='batch-design-dialog';dialog.className='batch-dialog';dialog.innerHTML=`<div class="batch-dialog-heading"><div><span class="eyebrow">TRAINING DATA PRODUCTION</span><h2>批量叶片设计方案</h2></div><button id="batch-close" aria-label="关闭批量方案">×</button></div><p class="batch-message" id="batch-message" role="status">设置设计空间后生成参数预览；发送到CFD后再启动计算。</p><div class="batch-design-layout"><section class="batch-card"><h3>01 · 基准与采样空间</h3><p id="batch-baseline"></p><button id="batch-use-current">使用当前叶片重新初始化</button><div class="batch-fields"><label>批次名称<input id="batch-name" maxlength="80" value="训练数据批次"></label><label>几何数量（含基准）<input id="batch-count" type="number" min="1" max="300" step="1" value="12"></label><label>随机种子<input id="batch-seed" type="number" min="0" max="2147483647" step="1" value="42"></label></div><div class="batch-table-scroll"><table><thead><tr><th>变量（最多6个）</th><th>下界</th><th>上界</th></tr></thead><tbody id="batch-bounds"></tbody></table></div><details><summary>让总师智能体建议采样方案</summary><label>设计目标与采样要求<textarea id="batch-instruction" rows="3" maxlength="6000">以当前叶型为基准，建议用于代理模型训练的少量变化变量及范围。说明经验假设和待验证项，保持二维冷态模板可用工况。</textarea></label><div class="batch-actions"><select id="batch-provider" aria-label="批次建议模型"><option value="general">通用大模型</option><option value="domain">航发领域大模型</option></select><button id="batch-ask-model">获取并填入建议</button></div><p id="batch-model-note">使用已保存的真实模型配置；建议填入后可编辑，再生成几何预览。</p></details></section><section class="batch-card"><h3>02 · 物理工况</h3><p>一个几何与一个工况组成一个独立CFD算例，单批最多1000个。</p><div class="batch-table-scroll"><table><thead><tr>${CONDITION_FIELDS.map(([,label])=>`<th>${label}</th>`).join('')}<th>操作</th></tr></thead><tbody id="batch-conditions"></tbody></table></div><button id="batch-add-condition">增加工况</button><p class="batch-muted">固定模板：二维 Pritchard 冷态叶栅。仅改变迭代次数不算新的物理工况。</p><div class="batch-actions"><button id="batch-generate" class="primary">生成并校验参数</button><button id="batch-stop-generation" disabled>取消生成</button></div><h3>03 · 参数预览与交接</h3><p id="batch-preview-summary">尚未生成参数。几何合法性由现有内核检查。</p><div class="batch-actions"><button id="batch-export" disabled>导出批量 JSON</button><button id="batch-to-cfd" class="primary" disabled>发送到 CFD 批次</button></div><div id="batch-previews" class="batch-previews"></div><details><summary>采样拒绝记录</summary><div id="batch-rejections"></div></details><details><summary>读取历史参数包</summary><div class="batch-actions"><button id="batch-load-designs">读取历史</button><select id="batch-design-history" aria-label="历史参数包"><option value="">尚未读取</option></select><button id="batch-open-design">载入预览</button></div></details></section></div>`;
  document.body.append(dialog);
  const cfdToggle=document.createElement('button');cfdToggle.id='cfd-batch-toggle';cfdToggle.textContent='批次仿真';cfdPanel.querySelector('.cfd-heading-actions').prepend(cfdToggle);
  const pane=document.createElement('section');pane.id='cfd-batch-pane';pane.hidden=true;pane.className='batch-workbench';pane.innerHTML=`<div class="batch-card"><div class="batch-actions"><h3>CFD 批次仿真</h3><button id="batch-refresh">连接 / 刷新批次</button><button id="batch-import">导入批量参数 JSON</button><button id="batch-new">返回初始设计生成参数</button></div><p id="batch-compute-note">批次使用当前平台后端的任务目录与计算环境；与单算例的独立服务连接分开。</p><p id="batch-cfd-message" class="batch-message" role="status">接收初始设计参数包或导入平台导出的批量JSON。</p><label>批次<select id="batch-select"><option value="">尚未读取</option></select></label><div class="batch-actions batch-control"><label>本批在途上限<input id="batch-inflight" type="number" min="1" max="8" step="1" value="2"></label><button id="batch-start" class="primary" disabled>启动 / 继续</button><button id="batch-pause" disabled>暂停新增提交</button><button id="batch-cancel" disabled>取消本批次</button><button id="batch-retry" disabled>重试选中失败项</button><button id="batch-open-ai" disabled>到 AI 构建数据集 ↗</button></div><p id="batch-summary">暂无批次。</p><p id="batch-template" class="batch-muted"></p><div class="batch-table-scroll batch-case-table"><table><thead><tr><th>选择</th><th>几何</th><th>工况</th><th>尝试</th><th>CFD状态</th><th>质量</th><th>任务</th><th>说明</th></tr></thead><tbody id="batch-cases"></tbody></table></div><div class="batch-actions"><button id="batch-export-run" disabled>导出批次记录</button><button id="batch-export-bundle" disabled>导出参数包</button></div></div>`;
  cfdPanel.append(pane);
  const aiCard=document.createElement('section');aiCard.className='ev-card batch-ai-card';aiCard.innerHTML=`<div class="ev-card-title"><h3>按 CFD 批次构建训练数据集</h3><button id="batch-ai-refresh">读取批次</button></div><p>只扫描所选批次的最新尝试；保留不收敛、缺失和未提交记录，不混入其他批次。</p><div class="batch-actions"><label>生产批次<select id="batch-ai-select"><option value="">尚未读取批次</option></select></label><label class="ev-check"><input id="batch-partial" type="checkbox">允许使用已结束的部分结果</label><button id="batch-build-dataset" class="primary" disabled>检查并构建数据集</button></div><p id="batch-ai-summary">数据集仍由现有CFD质量门槛筛选，并按独立几何分组。</p><p id="batch-ai-message" role="status"></p>`;
  aiPanel.querySelector('#ev-data').prepend(aiCard);
  const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.hidden=true;file.id='batch-file';document.body.append(file);
  async function api(path,body,timeout=20000){const response=await sessionFetch('/api/'+path,{...(body!==undefined?{method:'POST',body:JSON.stringify(body),headers:{'Content-Type':'application/json'}}:{}),signal:AbortSignal.timeout(timeout)});let data;try{data=await response.json();}catch{throw Error('批次接口不可用，请更新并重启后端');}if(!response.ok)throw Error(data.error||'批次请求失败');return data;}
  function message(text,error=false){for(const id of ['#batch-message','#batch-cfd-message','#batch-ai-message']){$(id).textContent=text;$(id).classList.toggle('batch-error',error);}}
  function handle(id,fn){$(id).onclick=async()=>{try{await fn();}catch(e){message(e.name==='TimeoutError'?'请求超时。请刷新核对已创建任务，避免重复操作。':e.message,true);}};}
  function markEdited(){editRevision++;requests.invalidate();if(bundle)$('#batch-preview-summary').textContent='方案已修改，下面是历史预览。请重新生成后交接。';previewButtons();}
  function previewButtons(){const valid=!!bundle&&previewRevision===editRevision&&!generationTask;$('#batch-export').disabled=!valid;$('#batch-to-cfd').disabled=!valid;$('#batch-generate').disabled=!!generationTask;$('#batch-stop-generation').disabled=!generationTask;}
  function setConditions(rows){$('#batch-conditions').innerHTML=rows.map((c,i)=>`<tr>${CONDITION_FIELDS.map(([k,,lo,hi])=>`<td><input type="number" min="${lo}" max="${hi}" step="${k==='iterations'?1:'any'}" data-condition="${k}" aria-label="工况${i+1} ${k}" value="${esc(c[k])}"></td>`).join('')}<td><button data-remove-condition="${i}" aria-label="删除工况${i+1}">移除</button></td></tr>`).join('');for(const button of dialog.querySelectorAll('[data-remove-condition]'))button.onclick=()=>{const values=readConditions();if(values.length<=1){message('至少保留一个工况',true);return;}values.splice(Number(button.dataset.removeCondition),1);setConditions(values);markEdited();};}
  function readConditions(){return [...dialog.querySelectorAll('#batch-conditions tr')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-condition]')].map(input=>[input.dataset.condition,Number(input.value)])));}
  function setBounds(bounds){$('#batch-bounds').innerHTML=FIELDS.map(([key,label,lo,hi,step,unit])=>{const v=baseline[key],delta=key==='bladeCount'?2:Math.max(Math.abs(v)*.05,step),b=bounds?.[key]||[Math.max(lo,v-delta),Math.min(hi,v+delta)];return `<tr data-bound="${key}"><th><label><input type="checkbox" ${bounds?bounds[key]?'checked':'':key==='radius'?'checked':''}>${esc(label)} <small>${unit}</small></label></th><td><input type="number" step="${key==='bladeCount'?1:'any'}" min="${lo}" max="${hi}" aria-label="${label}下界" value="${num(b[0])}"></td><td><input type="number" step="${key==='bladeCount'?1:'any'}" min="${lo}" max="${hi}" aria-label="${label}上界" value="${num(b[1])}"></td></tr>`;}).join('');}
  function useBaseline(useProposal=true){const proposal=useProposal?initialPanel.getBatchBaseline?.():null;baseline=validate(structuredClone(proposal?.parameters||getDesign()));if(baseline.model!=='pritchard-1985')throw Error('批量采样仅支持Pritchard叶型');analyze(baseline);provenance=proposal?.provenance||{source:'current-design'};$('#batch-baseline').textContent=`${proposal?'已生成的初设方案':'当前叶片设计'} · Cx ${num(baseline.axialChord)} mm · R ${num(baseline.radius)} mm · N ${baseline.bladeCount}`;setBounds();if(!$('#batch-conditions').children.length)setConditions([100200,100300,100400].map(p=>({inletTotalPressure:p,inletTotalTemperature:300,outletStaticPressure:100000,iterations:3000})));markEdited();}
  function plan(){if(!baseline)throw Error('请先选择有效基准');const bounds={};for(const row of dialog.querySelectorAll('[data-bound]'))if(row.querySelector('[type=checkbox]').checked)bounds[row.dataset.bound]=[...row.querySelectorAll('[type=number]')].map(input=>Number(input.value));return {name:$('#batch-name').value.trim(),baseline:structuredClone(baseline),bounds,count:Number($('#batch-count').value),seed:Number($('#batch-seed').value),conditions:readConditions(),provenance:structuredClone(provenance)};}
  function openDialog(){if(!dialog.open)dialog.showModal();if(!baseline)useBaseline();}
  function preview(result){bundle=result;previewRevision=editRevision;$('#batch-preview-summary').textContent=`有效几何 ${result.designs.length} / 目标 ${result.diagnostics.requested} · ${result.conditions.length} 工况 · ${result.case_count} 个算例 · 去重 ${result.diagnostics.duplicates||0} · 未补足 ${result.diagnostics.shortfall||0}`;$('#batch-previews').innerHTML=result.designs.slice(0,24).map(d=>`<article>${shape(d.parameters)}<strong>${esc(d.id)}</strong><small>R ${num(d.parameters.radius)} · Cx ${num(d.parameters.axialChord)}</small><button data-preview-design="${d.id}">查看参数</button></article>`).join('')+(result.designs.length>24?'<p>显示前24个叶型；完整参数保存在JSON包中。</p>':'');for(const button of dialog.querySelectorAll('[data-preview-design]'))button.onclick=()=>{const d=result.designs.find(d=>d.id===button.dataset.previewDesign);$('#batch-rejections').textContent=JSON.stringify({geometry:d.id,parameters:d.parameters},null,2);$('#batch-rejections').closest('details').open=true;};$('#batch-rejections').textContent=result.diagnostics.rejected?.length?JSON.stringify(result.diagnostics.rejected.slice(0,50),null,2):'没有几何拒绝记录。';previewButtons();}
  async function launchGeneration(kind,payload,importing=false){if(generationTask)throw Error('已有参数生成或导入任务运行');const gen=epoch,revision=editRevision,current=requests.previewTicket();const task=await api('evaluation/'+kind,payload);if(gen!==epoch)return;generationTask=task.id;previewButtons();message('正在校验批量几何，任务 '+task.id.slice(0,8));
    async function poll(){try{const t=await api('evaluation/tasks/'+task.id);if(gen!==epoch)return;if(terminal(t.status)){generationTask=null;previewButtons();if(t.status!=='completed'){message(t.message,true);return;}if(!current()){message('方案或预览已变化，本次结果保留在历史记录中。');return;}if(importing){preview(t.result);await handoff(t.result);}else if(revision===editRevision){preview(t.result);message('参数生成完成。请检查预览后发送到CFD批次。');}else message('生成任务已完成，但方案已被编辑。原参数包可从历史记录载入。');return;}message(t.message+' · '+task.id.slice(0,8));generationTimer=setTimeout(poll,1200);}catch(e){if(gen===epoch){message(e.message+'；正在重试读取任务状态。',true);generationTimer=setTimeout(poll,3000);}}}await poll();}
  async function handoff(result=bundle){if(!result)throw Error('请先生成有效参数包');const gen=epoch,b=await api('batches',{design_batch_id:result.id});if(gen!==epoch)return;batch=b;if(dialog.open)dialog.close();showBatch();await refreshBatches(b.id);message('批次已保存，尚未启动CFD。核对算例和在途上限后启动。');}
  function showBatch(){openCFD();pane.hidden=false;cfdPanel.dataset.cfdMode='batch';cfdToggle.textContent='返回单算例';}
  function saveJson(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function fillBatches(id,old){$(id).innerHTML=batchList.length?batchList.map(b=>`<option value="${b.id}">${esc(b.name)} · ${STATUS[b.status]||esc(b.status)} · ${b.case_count}算例</option>`).join(''):'<option value="">暂无批次</option>';if(batchList.some(b=>b.id===old))$(id).value=old;}
  async function refreshBatches(prefer){const serial=++listSerial,gen=epoch;const data=await api('batches');if(gen!==epoch||serial!==listSerial)return;batchList=data.batches;ready=data.cfd_ready;const chosen=prefer||$('#batch-select').value,aiChoice=$('#batch-ai-select').value;fillBatches('#batch-select',chosen);fillBatches('#batch-ai-select',prefer||aiChoice);$('#batch-compute-note').textContent=ready?'当前平台CFD后端已就绪。每批使用独立模板快照；全局计算槽位由服务器管理。':'当前为模型/数据服务，可保存批次。真实仿真需在同源OpenFOAM后端启动；不会模拟CFD结果。';if($('#batch-select').value){const b=await api('batches/'+$('#batch-select').value);if(gen!==epoch||serial!==listSerial)return;const changed=batch?.id!==b.id;batch=b;if(changed)$('#batch-inflight').value=b.max_in_flight;renderBatch();}renderAI();clearTimeout(pollTimer);if(batchList.some(b=>['running','cancelling'].includes(b.status)||Object.entries(b.counts).some(([k,v])=>v&&!terminal(k)&&!['pending','submitting'].includes(k))))pollTimer=setTimeout(()=>refreshBatches().catch(e=>message(e.message,true)),2200);}
  function renderBatch(){if(!batch)return;const selected=new Set([...pane.querySelectorAll('[data-case]:checked')].map(n=>n.dataset.case));const counts=Object.entries(batch.counts).map(([k,v])=>`${STATUS[k]||k} ${v}`).join(' / ');$('#batch-summary').textContent=`${batch.name} · ${batch.geometry_count}组几何 · ${batch.case_count}算例 · ${counts}。${batch.message}`;$('#batch-template').textContent=batch.template_digest?'已冻结模板 '+batch.template_digest.slice(0,16):'首次启动时冻结模板，后续重试继续使用此快照。';$('#batch-cases').innerHTML=batch.cases.map(c=>{const retry=['failed','cancelled','interrupted','unknown'].includes(c.status)||(c.status==='completed'&&c.quality==='rejected');return `<tr><td><input type="checkbox" data-case="${c.id}" aria-label="选择${c.geometry_id}/${c.condition_id}" ${retry?'':'disabled'} ${selected.has(c.id)?'checked':''}></td><td>${esc(c.geometry_id)}</td><td>${esc(c.condition_id)}</td><td>${c.attempt+1}</td><td>${STATUS[c.status]||esc(c.status)}</td><td>${c.quality==='accepted'?'通过':c.quality==='rejected'?'拒收':'待检查'}</td><td><code>${esc(c.job_id?.slice(0,8)||'—')}</code></td><td class="batch-reason">${esc(c.quality==='rejected'?c.quality_detail:c.error||'')}</td></tr>`;}).join('');$('#batch-start').disabled=!ready||busy||['running','cancelling'].includes(batch.status)||!batch.cases.some(c=>['pending','submitting'].includes(c.status));$('#batch-pause').disabled=busy||batch.status!=='running';$('#batch-cancel').disabled=busy||['completed','cancelled','cancelling'].includes(batch.status);$('#batch-retry').disabled=busy||['running','cancelling'].includes(batch.status);$('#batch-open-ai').disabled=false;$('#batch-export-run').disabled=false;$('#batch-export-bundle').disabled=false;$('#batch-inflight').disabled=batch.status==='running';}
  function renderAI(){const b=batchList.find(b=>b.id===$('#batch-ai-select').value);$('#batch-build-dataset').disabled=!b;$('#batch-ai-summary').textContent=b?`${b.geometry_count}组几何 / ${b.case_count}算例 · 已质检通过 ${b.quality_passed} · 已生成 ${b.dataset_ids?.length||0}个数据版本`:'数据集仍由现有CFD质量门槛筛选，并按独立几何分组。';}
  async function control(action,data={}){if(!batch||busy)return;await requests.control({id:batch.id,selected:()=>$('#batch-select').value,request:id=>api(`batches/${id}/${action}`,data),apply:b=>{batch=b;message(b.message);},refresh:id=>refreshBatches(id),busy:value=>{busy=value;renderBatch();}});}
  handle('#initial-batch',openDialog);handle('#batch-close',()=>dialog.close());handle('#batch-use-current',()=>useBaseline(false));handle('#batch-add-condition',()=>{const rows=readConditions();if(rows.length>=10)throw Error('最多10组工况');rows.push({...rows.at(-1),inletTotalPressure:Math.min(100500,rows.at(-1).inletTotalPressure+100)});setConditions(rows);markEdited();});
  for(const id of ['#batch-name','#batch-count','#batch-seed','#batch-bounds','#batch-conditions'])$(id).addEventListener('input',markEdited);
  handle('#batch-generate',()=>launchGeneration('batch_generate',{plan:plan()}));handle('#batch-stop-generation',async()=>{if(generationTask)await api('evaluation/tasks/'+generationTask+'/cancel',{});});handle('#batch-export',()=>saveJson(bundle,'aeroblade-batch-'+bundle.id.slice(0,8)+'.json'));handle('#batch-to-cfd',()=>handoff());
  handle('#batch-ask-model',async()=>{const gen=epoch,revision=editRevision;$('#batch-ask-model').disabled=true;message('正在请求真实大模型建议…');try{const reply=await api('design-assistant/batch-plan',{provider:$('#batch-provider').value,instruction:$('#batch-instruction').value,plan:plan()},130000);if(gen!==epoch)return;if(revision!==editRevision){message('请求期间方案已修改，未覆盖当前输入。请重新获取建议。');return;}$('#batch-model-note').textContent=reply.message;if(reply.plan){setBounds(reply.plan.bounds);setConditions(reply.plan.conditions);$('#batch-count').value=reply.plan.count;$('#batch-seed').value=reply.plan.seed;provenance=reply.plan.provenance;markEdited();message('模型建议已填入；请审阅范围和工况，再生成几何预览。');}}finally{$('#batch-ask-model').disabled=false;}});
  handle('#batch-load-designs',async()=>{const gen=epoch,r=await api('batches/designs');if(gen!==epoch)return;$('#batch-design-history').innerHTML=r.designs.map(d=>`<option value="${d.id}">${esc(d.name)} · ${d.geometry_count}几何 / ${d.case_count}算例</option>`).join('')||'<option value="">暂无参数包</option>';});handle('#batch-open-design',async()=>{const id=$('#batch-design-history').value;if(!id)throw Error('请选择历史参数包');const current=requests.previewTicket(),r=await api('batches/designs/'+id);if(current()){preview(r);message('已载入历史参数包，可直接交接；修改采样设置后需重新生成。');}});
  cfdToggle.onclick=()=>{if(pane.hidden){showBatch();refreshBatches().catch(e=>message(e.message,true));}else{pane.hidden=true;delete cfdPanel.dataset.cfdMode;cfdToggle.textContent='批次仿真';}};
  handle('#batch-refresh',()=>refreshBatches());handle('#batch-ai-refresh',()=>refreshBatches());handle('#batch-new',openDialog);handle('#batch-import',()=>file.click());
  file.onchange=async()=>{try{const chosen=file.files[0];if(!chosen)return;if(chosen.size>2_000_000)throw Error('参数包不能超过2MB');await launchGeneration('batch_import',{bundle:JSON.parse(await chosen.text())},true);}catch(e){message(e.message,true);}finally{file.value='';}};
  $('#batch-design-history').onchange=()=>requests.invalidate();$('#batch-select').onchange=()=>refreshBatches($('#batch-select').value).catch(e=>message(e.message,true));$('#batch-ai-select').onchange=renderAI;
  handle('#batch-start',()=>control('start',{max_in_flight:Number($('#batch-inflight').value)}));handle('#batch-pause',()=>control('pause'));handle('#batch-cancel',()=>control('cancel'));handle('#batch-retry',()=>control('retry',{case_ids:[...pane.querySelectorAll('[data-case]:checked')].map(n=>n.dataset.case)}));
  handle('#batch-open-ai',()=>{openAI();showTraining();$('#batch-ai-select').value=batch.id;renderAI();});handle('#batch-build-dataset',async()=>{const id=$('#batch-ai-select').value;if(!id)throw Error('请选择批次');await buildBatchDataset(id,$('#batch-partial').checked);message('批次数据集检查已提交；通过后将自动选中生成的数据版本。');});
  handle('#batch-export-run',()=>saveJson(batch,'aeroblade-run-'+batch.id.slice(0,8)+'.json'));handle('#batch-export-bundle',()=>saveJson(batch.manifest,'aeroblade-batch-'+batch.design_batch_id.slice(0,8)+'.json'));
  document.addEventListener('aeroblade:datasetbuilt',()=>refreshBatches().catch(e=>message(e.message,true)));
  document.addEventListener('aeroblade:sessionchange',e=>{if(e.detail.authenticated){hasSession=true;return;}if(!hasSession)return;hasSession=false;baseline=null;provenance={};editRevision++;previewRevision=-1;$('#batch-baseline').textContent='';$('#batch-bounds').replaceChildren();setConditions([{inletTotalPressure:100200,inletTotalTemperature:300,outletStaticPressure:100000,iterations:3000}]);for(const field of dialog.querySelectorAll('input,textarea')){if(field.type==='checkbox')field.checked=field.defaultChecked;else field.value=field.defaultValue;}$('#batch-provider').value='general';$('#batch-model-note').textContent='使用当前账号的模型配置';$('#batch-preview-summary').textContent='尚未生成';epoch++;listSerial++;requests.invalidate();busy=false;clearTimeout(pollTimer);clearTimeout(generationTimer);generationTask=null;bundle=null;batch=null;batchList=[];ready=false;if(dialog.open)dialog.close();$('#batch-cases').textContent='';$('#batch-previews').textContent='';$('#batch-rejections').textContent='';fillBatches('#batch-select','');fillBatches('#batch-ai-select','');$('#batch-design-history').innerHTML='<option value="">尚未读取</option>';for(const id of ['#batch-start','#batch-pause','#batch-cancel','#batch-retry','#batch-open-ai','#batch-export-run','#batch-export-bundle'])$(id).disabled=true;previewButtons();renderAI();message('已退出登录；服务器批次继续运行。');});
  return {showBatch};
}
